# Generated by Django 4.1.2 on 2023-04-11 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_name',
                'verbose_name_plural': 'User_names',
            },
        ),
        migrations.CreateModel(
            name='User_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('organizations', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=False)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_works', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'User_work',
                'verbose_name_plural': 'User_works',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('orga_of_education', models.CharField(max_length=255)),
                ('year_of_graduation', models.IntegerField(default=False)),
                ('specialist_certificate', models.CharField(max_length=255)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'User_infos',
            },
        ),
        migrations.CreateModel(
            name='User_birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_births', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'User_birth',
                'verbose_name_plural': 'User_births',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=False)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal', models.CharField(max_length=255)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criminals', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Criminal',
                'verbose_name_plural': 'Criminals',
            },
        ),
    ]
