# Generated by Django 4.1.2 on 2023-04-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='specialist_certificate',
        ),
    ]
