# Generated by Django 4.1.2 on 2023-04-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0002_remove_user_info_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='information',
        ),
        migrations.RemoveField(
            model_name='user_work',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user_work',
            name='position',
        ),
    ]
