# Generated by Django 4.1.2 on 2023-04-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0003_remove_practice_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_work',
            old_name='organizations',
            new_name='organization',
        ),
    ]
