# Generated by Django 4.1.2 on 2023-04-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0004_rename_organizations_user_work_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='criminal',
            new_name='criminal_record',
        ),
    ]
