# Generated by Django 4.1.2 on 2023-04-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0011_alter_doctor_doctor_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_teaching', models.CharField(max_length=255)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_degree', models.CharField(max_length=255)),
                ('year_of_appropriation', models.IntegerField(default=False)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docent_professor', models.CharField(max_length=255)),
                ('year_of_appropriation', models.IntegerField(default=False)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='Phd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_record', models.CharField(max_length=255)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phdes', to='info1.user_name')),
            ],
            options={
                'verbose_name': 'Phd',
                'verbose_name_plural': 'Phds',
            },
        ),
    ]
