# Generated by Django 4.1.2 on 2023-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0012_subject_sport_professor_phd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
