# Generated by Django 4.1.2 on 2023-04-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0013_alter_doctor_doctor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='year_of_appropriation',
        ),
    ]
