# Generated by Django 4.1.2 on 2023-04-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info1', '0014_remove_sport_year_of_appropriation'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='magistr_specialization',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='master',
            name='magistr_year_of_graduation',
            field=models.IntegerField(default=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'DEAN '), (2, 'ADVISER')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
