# Generated by Django 4.1.2 on 2023-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info1', '0016_alter_master_magistr_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='magistr_specialization',
        ),
        migrations.RemoveField(
            model_name='master',
            name='magistr_year_of_graduation',
        ),
    ]
