# Generated by Django 4.1.2 on 2023-04-22 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info1', '0022_alter_user_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_birth',
            name='date_of_birth',
            field=models.DateField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='user_birth',
            name='place_of_birth',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos', to='info1.user_name'),
        ),
        migrations.AlterField(
            model_name='user_name',
            name='firstname',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_name',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_name',
            name='secondname',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
